Здесь представлены файлы решение курса от Яндекс Лицея по языку программирования GoLang. 
 https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.00'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
